services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: backend
    container_name: mcm_backend
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DATASOURCE_USERNAME: ${DB_USER}
      DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: mcm_frontend
    build:
      context: frontend
      target: ${ENVIRONMENT-development}
    ports:
      - "${FRONTEND_PORT:-80}:80"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    environment:
      REACT_APP_USING_DOCKER: "true"
      NODE_ENV: development # TODO Investigate

    depends_on:
      backend:
        condition: service_healthy

    networks:
      - frontend
      - backend # So the frontend can reach the backend


volumes:
  db_data:

networks:
  db:
      internal: false
  backend:
      internal: false # So compiler can download packages (TODO find fix)
  frontend:
      internal: false
