version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

  backend:
    build:
      context: backend
    container_name: mcm_backend
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DATASOURCE_USERNAME: ${DB_USER}
      DATASOURCE_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
