.PHONY: setup up

setup:
	@if [ ! -f .env ]; then \
		echo "Enter the port number MCM should run at (default: 8080):"; \
		read FRONTEND_PORT; \
		FRONTEND_PORT=$${FRONTEND_PORT:-8080}; \
		echo "Enter MCM default user password (default: autogenerated):"; \
		read FRONTEND_DEFAULT_USER_PASSWORD; \
		FRONTEND_DEFAULT_USER_PASSWORD=$${FRONTEND_DEFAULT_USER_PASSWORD:-$$(openssl rand -base64 32)}; \
		FRONTEND_DEFAULT_USERNAME=admin; \
		DB_PASSWORD=$$(openssl rand -base64 32); \
		DB_NAME=mcm_db; \
		DB_USER=mcm_db_user; \
		echo "# Custom environment variables for MCM" > .env; \
		echo "" >> .env; \
		echo "# Front-end variables:" >> .env; \
		echo "FRONTEND_PORT=$$FRONTEND_PORT" >> .env; \
		echo "FRONTEND_DEFAULT_USER_PASSWORD=\"$$FRONTEND_DEFAULT_USER_PASSWORD\" # NOTE: If changed the db_volume must be deleted in order for this to be updated" >> .env; \
		echo "" >> .env; \
        echo "# Database variables:" >> .env; \
		echo "DB_NAME=\"$$DB_NAME\"" >> .env; \
		echo "DB_USER=\"$$DB_USER\"" >> .env; \
		echo "DB_PASSWORD=\"$$DB_PASSWORD\"" >> .env; \
		echo ""; \
		echo "-----"; \
		echo ""; \
		echo "Created environments, you can always change them at .env"; \
		echo ""; \
		echo "Once MCM is running you can login at:"; \
		echo "Host: http://localhost:$$FRONTEND_PORT"; \
		echo "Username: $$FRONTEND_DEFAULT_USERNAME"; \
		echo "Password: $$FRONTEND_DEFAULT_USER_PASSWORD"; \
		echo ""; \
	else \
		echo ".env file already exists. Delete it to reconfigure."; \
	fi

up: setup
	docker compose --env-file .env up -d
