.PHONY: setup up

setup:
	@if [ ! -f .env ]; then \
		echo "Enter API_KEY (default: autogenerated):"; \
		read API_KEY; \
		API_KEY=$${API_KEY:-$$(openssl rand -base64 32)}; \
		echo "Enter PORT (default: 8080):"; \
		read PORT; \
		PORT=$${PORT:-8080}; \
		echo "Enter DB_PASSWORD (default: autogenerated):"; \
		read DB_PASSWORD; \
		DB_PASSWORD=$${DB_PASSWORD:-$$(openssl rand -base64 32)}; \
		echo "API_KEY=$$API_KEY" > .env; \
		echo "PORT=$$PORT" >> .env; \
		echo "DB_PASSWORD=$$DB_PASSWORD" >> .env; \
	else \
		echo ".env file already exists. Delete it to reconfigure."; \
	fi

up: setup
	docker-compose up -d
