spring.application.name=backend

# Multipart upload limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

# Tomcat: -1 disables swallow-size limit
server.tomcat.max-swallow-size=-1